# **Универсальные функции**

Унгиверсальной функцией, или *u-функцией*, называется функция, которая выполняет поэлементные операции над данными, хранящимися в объектах `ndarray`. Можно считать, что это векторные обертки вокруг простых функций, которые принимают одно или несколько скалярных значений и порождают один или несколько скалярных результатов.

Многие u-функции — простые поэлементные преобразования, например, `sqrt` или `exp`:

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr) #извлекает квадратный корень

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Такие u-функции называются *унарными*. Другие, например, `add` или `maximum`, принимают два массива (и поэтому называются *бинарными*) и возвращают один результирующий массив:

In [ ]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.14560795, -0.70956578, -0.29279364, -1.93215618,  0.40873229,
       -0.61324226,  1.28916129, -0.05923542])

In [ ]:
y

array([ 0.34193515,  0.21329422, -0.65311945,  0.7335896 , -1.80012215,
       -0.39655122,  1.50314029, -0.05885306])

In [ ]:
np.maximum(x, y)

array([ 0.34193515,  0.21329422, -0.29279364,  0.7335896 ,  0.40873229,
       -0.39655122,  1.50314029, -0.05885306])

Здесь `numpy.maximum` вычисляет поэлементные максимумы в массивах `x` и `y`.

Хотя и нечасто, но можно встретить u-функцию, возвращающую несколько массивов. Примером может служить `modf`, векторный встроенной в Python функции `divmod`: она возвращает дробные и целые части хранящихся в массиве чисел с плавающей точкой:


In [ ]:
arr = np.random.randn(7) * 5
arr

array([-8.47067664, -0.51806125,  2.27194341, -2.57139662, -1.55745904,
        2.90440094, 13.9869936 ])

In [ ]:
remainder, whole_part = np.modf(arr) # remainder - переменная дробной части, whole_part - переменная целой части

In [ ]:
remainder

array([-0.47067664, -0.51806125,  0.27194341, -0.57139662, -0.55745904,
        0.90440094,  0.9869936 ])

In [ ]:
whole_part

array([-8., -0.,  2., -2., -1.,  2., 13.])

**Унитарные u-функции**

In [ ]:
abs, fabs #	Вычислить абсолютное значение целых, вещественных или комплексных элементов массива. Для вещественных данных fabs работает быстрее
sqrt #	Вычислить квадратный корень из каждого элемента. Эквивалентно arr ** 0.5
square #	Вычислить квадрат каждого элемента. Эквивалентно arr ** 2
exp #	Вычислить экспоненту ex каждого элемента
log, log10, log2, log1p #	Натуральный (по основанию e), десятичный, двоичный логарифм и функция
            log(1 + x) # соответственно
sign #	Вычислить знак каждого элемента: 1 (для положительных чисел), 0 (для нуля) или –1 (для отрицательных чисел)
ceil #	Вычислить для каждого элемента наименьшее целое число, не меньшее его
floor #	Вычислить для каждого элемента наибольшее целое число, не большее его
rint #	Округлить элементы до ближайшего целого с сохранением dtype
modf #	Вернуть дробные и целые части массива в виде отдельных массивов
isnan #	Вернуть булев массив, показывающий, какие значения являются NaN (нечислами)
isfinite, isinf # Вернуть булев массив, показывающий, какие элементы являются конечными (не inf и не NaN) или бесконечными соответственно
cos, cosh, sin, sinh,tan, tanh # Обычные и гиперболические тригонометрические функции
arccos, arccosh, arcsin, arcsinh, arctan, arctanh #Обратные тригонометрические функции
logical_not # Вычислить значение истинности not x для каждого элемента. Эквивалентно –arr

**Бинарные u-функции**

In [ ]:
add #Сложить соответственные элементы массивов
subtract #Вычесть элементы второго массива из соответственных элементов первого
multiply #Перемножить соответственные элементы массивов
divide, floor_divide #Деление и деление с отбрасыванием остатка
power #Возвести элементы первого массива в степени, указанные во втором массиве
maximum, fmax #Поэлементный максимум. Функция fmax игнорирует значения NaN
minimum, fmin#Поэлементный минимум. Функция fmin игнорирует значения NaN
mod #Поэлементный модуль (остаток от деления)
copysign #Копировать знаки значений второго массива в соответственные элементы первого массива
greater, greater_equal, less, less_equal, equal, not_equal #Поэлементное сравнение, возвращается булев массив. Эквивалентны инфиксным операторам >, >=, <, <=, ==, !=
logical_and, logical_or, logical_xor #Вычислить логическое значение истинности логических операций. Эквивалентны инфиксным операторам &, |, ^