# **Линейная алгебра**

Линейно-алгебраические операции: умножение и разложение матриц, вычисление определителей и другие — важная часть любой библиотеки для работы с массивами. В отличие от MATLAB, в NumPy применение оператора `*` к двум двумерным массивам вычисляет поэлементное, а не матричное произведение. А для перемножения матриц используется функция `dot` — в виде как метода массива, так и функции в пространстве имен `numpy`:

In [2]:
import numpy as np

In [3]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])

In [4]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [6]:
x.dot(y) #умножает матрицу x на матрицу y

array([[ 28.,  64.],
       [ 67., 181.]])

`x.dot(y)` эквивалентно `np.dot(x, y)`:

In [7]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

Произведение двумерного массива и одномерного массива подходящего размера дает одномерный массив:

In [11]:
np.dot(x, np.ones(3)) #умножает матрицу x на матрицу из единиц

array([ 6., 15.])

Символ `@` также может использоваться в роли инфиксного оператора умножения матриц:

In [12]:
x @ np.ones(3) #умножает матрицу x на матрицу из единиц

array([ 6., 15.])

В модуле `numpy.linalg` имеется стандартный набор алгоритмов, в частности, разложение матриц, нахождение обратной матрицы и вычисление определителя:

In [23]:
from numpy.linalg import inv, qr

In [24]:
X = np.random.randn(5,5)

In [25]:
mat = X.T.dot(X) #вычисляет произведение матрицы X на транспонированную к ней матрицу X.T
mat

array([[20.41006094,  5.97058397,  3.06305421, -0.28806935,  3.5666257 ],
       [ 5.97058397,  3.4986698 ,  2.70451028, -0.68652574,  0.61347143],
       [ 3.06305421,  2.70451028,  5.10288401, -2.34709952, -1.45136577],
       [-0.28806935, -0.68652574, -2.34709952,  1.75843589,  0.62571904],
       [ 3.5666257 ,  0.61347143, -1.45136577,  0.62571904,  2.00390745]])

In [26]:
mat.dot(inv(mat)) #вычисляет произведение матрицы mat на транспонированную к ней матрицу

array([[ 1.00000000e+00,  1.48754001e-15, -1.00462488e-14,
        -4.78906452e-16,  3.01997547e-15],
       [-4.21118962e-16,  1.00000000e+00, -7.46417887e-15,
        -1.83548484e-15, -4.32895525e-15],
       [-4.86959201e-16, -2.16935673e-15,  1.00000000e+00,
         7.76418224e-15,  3.08045145e-15],
       [ 4.28104805e-16,  1.16564420e-15, -4.98468886e-15,
         1.00000000e+00, -4.09365001e-15],
       [ 2.57646736e-16,  1.62380735e-16, -4.84836879e-15,
        -2.29612006e-15,  1.00000000e+00]])

In [27]:
q, r = qr(mat) #
r

array([[-21.78083021,  -7.0437598 ,  -4.12264764,   0.70900013,
         -3.62608566],
       [  0.        ,  -2.53693751,  -5.21622869,   2.48289443,
          2.05979454],
       [  0.        ,   0.        ,  -2.47914816,   1.5638972 ,
          1.37304626],
       [  0.        ,   0.        ,   0.        ,  -0.65846668,
          0.57495712],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.06095605]])

Наиболее употребительные функции из модуля `numpy.linalg`:

In [ ]:
diag #возвращает диагональные элементы квадратной матрицы в виде одномерного массива или преобразует одномерный массив в квадратную матрицу, в которой все элементы, кроме находящихся на главной диагонали, равны нулю
dot #вычисляет произведение матриц
trace #вычисляет след матрицы — сумму диагональных элементов
det #вычисляет определитель матрицы
eig #вычисляет собственные значения и собственные векторы квадратной матрицы
inv #вычисляет обратную матрицу
pinv #вычисляет псевдообратную матрицу Мура-Пенроуза для квадратной матрицы
qr #вычисляет QR-разложение
svd #вычисляет сингулярное разложение (SVD)
solve #решает линейную систему Ax = b, где A – квадратная матрица
lstsq #в ычисляет решение уравнения y = Xb по методу наименьших квадратов